# Generated by Django 4.2.5 on 2023-09-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_rename_customer_order_id_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_products',
            new_name='products',
        ),
    ]
